// examples/react-app/src/components/Counter.tsx
import { useMeat } from '@meat/plugins/react/useMeat';
import meat from '@meat';

export default function Counter() {
  const count = useMeat<number>('count');

  function increment() {
    meat.set('count', count + 1);
  }

  return (
    <div>
      <button onClick={increment}>Increment</button>
      <p>MEAT count: {count}</p>
    </div>
  );
}

// examples/qwik-demo/src/components/Counter.tsx
import { component$ } from '@builder.io/qwik';
import { useMeat } from '../../src/plugins/qwik/useMeat';

export const Counter = component$(() => {
  const count = useMeat('count');

  return (
    <>
      <button onClick$={() => count.value++}>Increment</button>
      <p>MEAT count: {count.value}</p>
    </>
  );
});
