// examples/solid-demo/src/App.tsx
import { Component } from 'solid-js';
import { useMeat } from './useMeat';
import meat from '../../../src/meat.ts';

const App: Component = () => {
  const count = useMeat('count');

  return (
    <main>
      <h1>MEAT + SolidJS Demo</h1>
      <button onClick={() => meat.set('count', count() + 1)}>Increment</button>
      <p>MEAT count: {count()}</p>
    </main>
  );
};

export default App;

// examples/nuxt-app/app.vue
<script setup lang="ts">
import { useMeat } from '../src/plugins/nuxt/useMeat.ts';
import meat from '../../../src/meat.ts';

const count = useMeat('count');

function increment() {
  meat.set('count', count.value + 1);
}
</script>

<template>
  <main>
    <h1>MEAT + Nuxt Demo</h1>
    <button @click="increment">Increment</button>
    <p>MEAT count: {{ count }}</p>
  </main>
</template>
