// examples/next-app/components/Counter.tsx
import { useMeat } from '../../../src/plugins/next/useMeat';
import meat from '../../../src/meat.ts';

export default function Counter() {
  const count = useMeat('count');

  function increment() {
    meat.set('count', count + 1);
  }

  return (
    <div>
      <button onClick={increment}>Increment</button>
      <p>MEAT count: {count}</p>
    </div>
  );
}

// examples/angular-demo/src/app/counter.component.ts
import { Component, OnInit } from '@angular/core';
import { MeatService } from '../../../src/plugins/angular/meatAngularPlugin';

@Component({
  selector: 'app-counter',
  template: `
    <button (click)="increment()">Increment</button>
    <p>MEAT count: {{ count }}</p>
  `
})
export class CounterComponent implements OnInit {
  count = 0;

  constructor(private meat: MeatService) {}

  ngOnInit() {
    this.meat.subscribe('count', val => this.count = val);
  }

  increment() {
    this.meat.set('count', this.count + 1);
  }
}
